// Enumération étendue des noms d'icônes disponibles avec plus d'options
export enum IconName {
  // Actions générales
  Save = 'save',
  Edit = 'pencil',
  Delete = 'delete',
  Add = 'plus',
  Minus = 'minus',
  Back = 'arrow-left',
  Forward = 'arrow-right',
  Home = 'home',
  Menu = 'menu',
  Close = 'close',
  Login = 'login',
  Logout = 'logout',
  Profile = 'account',
  Success = 'check-circle',
  Failed = 'close-circle',
  Warning = 'alert',
  Info = 'information',
  Settings = 'cog',
  Refresh = 'refresh',
  Search = 'magnify',
  Filter = 'filter',
  Phone = 'phone',
  Email = 'email',
  Share = 'share-variant',
  Send = 'send',
  Download = 'download',
  Upload = 'upload',
  Print = 'printer',
  Copy = 'content-copy',
  Paste = 'clipboard-paste',
  Cut = 'content-cut',
  Folder = 'folder',
  File = 'file',
  Camera = 'camera',
  Image = 'image',
  Video = 'video',
  Music = 'music',
  Calendar = 'calendar',
  Clock = 'clock',
  Map = 'map',
  Location = 'map-marker',
  Food = 'food',
  MedicalBag = 'medical-bag',
  ChartBar = 'chart-bar',
  
  // Navigation et interface
  ChevronUp = 'chevron-up',
  ChevronDown = 'chevron-down',
  ChevronLeft = 'chevron-left',
  ChevronRight = 'chevron-right',
  ArrowUp = 'arrow-up',
  ArrowDown = 'arrow-down',
  Play = 'play',
  Pause = 'pause',
  Stop = 'stop',
  Expand = 'arrow-expand',
  Minimize = 'arrow-collapse',
  Eye = 'eye',
  EyeOff = 'eye-off',
  Lock = 'lock',
  Unlock = 'lock-open',
  
  Barn = 'barn',
  Growth = 'chart-line',
  Scale = 'scale-balance',
  Timeline = 'timeline',
  
  // Icônes spécifiques à l'agriculture
  Agriculture = 'tractor',
  Elevage = 'cow',
  Tractor = 'tractor',
  Harvest = 'wheat',
  Plant = 'sprout',
  Wheat = 'wheat',
  Apple = 'apple',
  Carrot = 'carrot',
  Tree = 'tree',
  Pool = 'pool',
  FishFood = 'food',
  Water = 'water',
  Seed = 'seed',
  Flower = 'flower',
  Leaf = 'leaf',
  Sun = 'weather-sunny',
  Cloud = 'weather-cloudy',
  Rain = 'weather-rainy',
  
  // Icônes spécifiques à l'élevage
  Avicole = 'bird',
  Bovin = 'cow',
  Ovin = 'sheep',
  Caprin = 'goat',
  Piscicole = 'fish',
  Egg = 'egg',
  Milk = 'cow',
  Chicken = 'chicken',
  Farm = 'barn',
  Feed = 'grass',
  
  // Icônes métier et statistiques
  Chart = 'chart-bar',
  LineChart = 'chart-line',
  PieChart = 'chart-pie',
  Analytics = 'chart-areaspline',
  Report = 'file-document',
  Statistics = 'chart-arc',
  Money = 'cash',
  Calculator = 'calculator',
  Database = 'database',
  Server = 'server',
}